import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  index('routes/marketing/home.tsx'),
  route('about', 'routes/marketing/about.tsx'),
  route('contact', 'routes/marketing/contact.tsx'),
  route('privacy', 'routes/marketing/privacy.tsx'),
  route('privacy-policy', 'routes/marketing/privacy-policy.tsx'),
  route('cookies', 'routes/marketing/cookies.tsx'),
  route('terms', 'routes/marketing/terms.tsx'),
  route('community-rules', 'routes/marketing/community-rules.tsx'),
  route('community-request', 'routes/marketing/community-request.tsx'),
  route('faq', 'routes/marketing/faq.tsx'),
  route('attributions', 'routes/marketing/attributions.tsx'),
  route('app', 'routes/app/app.tsx'),
  route('app/search', 'routes/app/search.tsx'),
  route('app/messages', 'routes/app/messages.tsx'),
  route('app/messages/conversation/:conversationId', 'routes/app/messages-conversation.tsx'),
  route('app/messages/channel/:channelId', 'routes/app/messages-channel.tsx'),
  route('app/notifications', 'routes/app/notifications.tsx'),
  route('app/post/:postId/comments', 'routes/app/post-comments.tsx'),
  route('app/community/:communityId', 'routes/app/community.tsx'),
  route('app/profile', 'routes/app/profile.tsx'),
  route('app/profile/edit', 'routes/app/profile-edit.tsx'),
  route('app/settings', 'routes/app/settings.tsx'),
  route('app/profile/anon/:anonProfileId', 'routes/app/profile-anon.tsx'),
  route('app/profile/anonymous', 'routes/app/profile-anonymous.tsx'),
  route('app/profile/:userId/followers', 'routes/app/profile-followers.tsx'),
  route('app/profile/:userId/following', 'routes/app/profile-following.tsx'),
  route('app/profile/:userId', 'routes/app/profile-user.tsx'),
  route('login', 'routes/marketing/login.tsx'),
  route('delete-account', 'routes/marketing/delete-account.tsx'),
] satisfies RouteConfig;
