import { type RouteConfig, index, route } from '@react-router/dev/routes';

export default [
  route('.well-known/apple-app-site-association', 'routes/marketing/apple-app-site-association.tsx'),
  route('favicon.ico', 'routes/marketing/favicon-ico.tsx'),
  route('robots.txt', 'routes/marketing/robots.tsx'),
  route('sitemap.xml', 'routes/marketing/sitemap.tsx'),
  index('routes/marketing/home.tsx'),
  route('about', 'routes/marketing/about.tsx'),
  route('contact', 'routes/marketing/contact.tsx'),
  route('privacy', 'routes/marketing/privacy.tsx'),
  route('privacy-policy', 'routes/marketing/privacy-policy.tsx'),
  route('cookies', 'routes/marketing/cookies.tsx'),
  route('terms', 'routes/marketing/terms.tsx'),
  route('community-rules', 'routes/marketing/community-rules.tsx'),
  route('community-request', 'routes/marketing/community-request.tsx'),
  route('faq', 'routes/marketing/faq.tsx'),
  route('attributions', 'routes/marketing/attributions.tsx'),
  route('p/:postId', 'routes/marketing/post-share.tsx'),
  route('c/:communityId', 'routes/marketing/community-share.tsx'),
  route('app', 'routes/app/app.tsx'),
  route('app/search', 'routes/app/search.tsx'),
  route('app/hashtags/:hashtag', 'routes/app/hashtag.tsx'),
  route('app/messages', 'routes/app/messages.tsx'),
  route('app/messages/conversation/:conversationId', 'routes/app/messages-conversation.tsx'),
  route('app/messages/channel/:channelId', 'routes/app/messages-channel.tsx'),
  route('app/notifications', 'routes/app/notifications.tsx'),
  route('app/post/:postId/comments', 'routes/app/post-comments.tsx'),
  route('app/community/:communityId', 'routes/app/community.tsx'),
  route('app/profile', 'routes/app/profile.tsx'),
  route('app/create', 'routes/app/create.tsx'),
  route('app/profile/edit', 'routes/app/profile-edit.tsx'),
  route('app/settings', 'routes/app/settings.tsx'),
  route('app/settings/blocked', 'routes/app/settings-blocked.tsx'),
  route('app/settings/verifications', 'routes/app/settings-verifications.tsx'),
  route('app/settings/review', 'routes/app/settings-review.tsx'),
  route('app/settings/connected', 'routes/app/settings-connected.tsx'),
  route('app/settings/content', 'routes/app/settings-content.tsx'),
  route('app/profile/anon/:anonProfileId', 'routes/app/profile-anon.tsx'),
  route('app/profile/anonymous', 'routes/app/profile-anonymous.tsx'),
  route('app/profile/:userId/followers', 'routes/app/profile-followers.tsx'),
  route('app/profile/:userId/following', 'routes/app/profile-following.tsx'),
  route('app/profile/:userId', 'routes/app/profile-user.tsx'),
  route('login', 'routes/marketing/login.tsx'),
  route('signup', 'routes/marketing/signup.tsx'),
  route('onboarding', 'routes/marketing/onboarding.tsx'),
  route('delete-account', 'routes/marketing/delete-account.tsx'),
  route('u/:username', 'routes/marketing/profile-share.tsx'),
] satisfies RouteConfig;
